# Generated by Django 3.1.3 on 2020-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='lastReviewed',
            new_name='last_reviewed',
        ),
    ]
