# Generated by Django 3.1.3 on 2020-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20201119_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
