# Generated by Django 3.1.3 on 2020-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='lastReviewedAt',
            new_name='last_reviewed_at',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='nextReviewAt',
            new_name='next_review_at',
        ),
    ]
