# Generated by Django 3.1.3 on 2020-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20201119_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
